### ISSUE TITLE
Is author made mistake ?

### ISSUE THREAD

**Issue by tstepnik** [tstepnik/simple-mistakes#1]
Task's author write that if we place only line with scanner.nextdouble() in try/catch the output in console will be wrong, but i did that and everything is correct, what do you think ?
example from java start:
![image](https://user-images.githubusercontent.com/60854334/75270944-b4cd9080-57fb-11ea-8511-d98b3d769ca6.png)

My code:
![image](https://user-images.githubusercontent.com/60854334/75271014-d3338c00-57fb-11ea-88ca-b03afdf5b5f6.png)

My output:
![image](https://user-images.githubusercontent.com/60854334/75271061-e6465c00-57fb-11ea-95a3-14b2bba54a7f.png)

**Comment by rbobko93** [comment]
I also don't understand why it would fail. Let's leave it as it is for now. Also, stop putting your code (or any code snippets) as screenshots. Use markdown formatting.

**Comment by tstepnik** [comment]
No i know why, because i had two loops ;)

**Comment by rbobko93** [comment]
I guess we can close this issue then.
